### ISSUE TITLE
Delete TEI relation to EpiDoc

### ISSUE THREAD

**Issue by kmpenner** [biblenerd/awesome-bible-developer-resources#1]
Remove "by the EpiDoc international community".
EpiDoc specifies a subset of TEI; TEI is not part of EpiDoc.

**Comment by biblenerd** [comment]
Thank you! Fixed with commit https://github.com/biblenerd/awesome-bible-developer-resources/commit/74066a038f5387b8296d4d5ae3432863190a3c2e
